#!/usr/bin/env python
# -*- coding: utf-8 -*-

import Tables

import os
import glob
import logging
import datetime
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
import sqlalchemy.orm.exc


from Operations import *


###############################################################################
# Plist reader:

import plistlib

class DiagnosticLoader:
	def __init__(self, _session, _dirName):
		self.__session = _session
		self.__launch = Tables.Launch( time = datetime.datetime.now(), name = _dirName )
		self.__session.add( self.__launch )
		self.__session.commit()

	def getOrCreate(self, _table, **_kwargs):
	    instance = self.__session.query(_table).filter_by(**_kwargs).first()
	    if instance:
	        return instance, False
	    else:
	        instance = _table(**_kwargs)
	        self.__session.add(instance)
	        return instance, True

	def load( self, _plistFileName ):
		with open(_plistFileName, 'rb') as fp:
			plist = plistlib.readPlist(fp)
			self.createDiagnosticsFromDict( plist )

	def getFile( self, _fileName ):
		return self.getOrCreate( Tables.File, name = _fileName )[0]

	def createPath( self, _fileNames, _plist):
		# TODO support control flow path piece
		pieceId = 0
		for piecePl in _plist:
			if piecePl['kind'] != 'event':
				continue
			pathPiece, created = self.getOrCreate(Tables.PathPiece, 
			    message             = piecePl['message'],
			    extended_message    = piecePl['extended_message'],
			    depth               = piecePl['depth'],
			    piece_id            = pieceId,
			    line                = piecePl['location']['line'],
			    col                 = piecePl['location']['col'],
			    file                = self.getFile( _fileNames[ piecePl['location']['file'] ] )	
			)
			pieceId = pieceId + 1
			pathPiece.launches.append( self.__launch )
			yield pathPiece, created



	def createDiagnosticsFromDict( self, _plist ):
		fileNames = _plist[ 'files' ]
		diagnosticsPl = _plist[ 'diagnostics' ]
		

		for diagPl in diagnosticsPl:
			uniqueId = diagPl['issue_hash']
			diag, created = self.getOrCreate( Tables.Diagnostic, issue_hash = uniqueId )
			if created:
				diag.description        		= diagPl['description']
				diag.category           		= diagPl['category']
				diag.type               		= diagPl['type']
				diag.issue_context_kind 		= diagPl['issue_context_kind']
				diag.issue_context   			= diagPl['issue_context']  
				diag.issue_hash					= diagPl['issue_hash']                     
				diag.line               		= diagPl['location']['line']
				diag.col                		= diagPl['location']['col']
				diag.file              			= self.getFile( fileNames[ diagPl['location']['file'] ] )
				diag.false_positive				= False
			
			diag.launches.append( self.__launch  )
			for piece, peaceCreated in self.createPath( fileNames, diagPl['path'] ):
				if peaceCreated:
					diag.all_path_pieces.append( piece )
			# TODO: Maybe autorefreshing would be better?
			self.__session.commit()


###############################################################################
# Command executors:

class DatabaseAccessProblem( BaseException ):
	pass

class NoInitializedDatabase( DatabaseAccessProblem ):
	pass


class AddCommandExecutor( CommandExecutor ):
	def __init__( self, **_args ):
		super( AddCommandExecutor, self ).__init__( os.getcwd() )
		self.__resultsDir = os.path.abspath( _args['result_dir'] )
		self.__loadManyLaunches = ( 'fewruns' in _args )

	def loadDiagnostics( self, _dir ):
		self.checkDatabaseAvailability()
		files = glob.glob( _dir + '/*.plist' )
		if not files:
			print( "WARNING: No plist files are presented in " + self.__resultsDir )

		session = self.connect()
		diagLoader = DiagnosticLoader( session, _dir )
		for file in files:
			diagLoader.load( file )

	def execute( self ):
		if not self.__loadManyLaunches:
			self.loadDiagnostics( self.__resultsDir )
			return

		for name in sorted( os.listdir(self.__resultsDir) ):
			absPath = os.path.join(self.__resultsDir, name)
			if os.path.isdir(absPath):
				self.loadDiagnostics( absPath )
				print "Added diagnostics from " + absPath


class LogCommandExecutor( CommandExecutor ):
	def __init__( self, **_args ):
		super( LogCommandExecutor, self ).__init__( os.getcwd() )
	
	def getIndent( self ):
		return '\t'

	def showDifference( self, _oldLaunch, _newLaunch ):
		newDiagnostics 	= set( _newLaunch.valid_diagnostics )
		oldDiagnostics 	= set( _oldLaunch.valid_diagnostics )
		fixed 			= oldDiagnostics.difference( newDiagnostics )
		notFixed 		= newDiagnostics.intersection( oldDiagnostics )
		new				= newDiagnostics.difference( oldDiagnostics )
		print (self.getIndent() + "Fixed diagnostics:           " + str( len( fixed )) 	) 
		print (self.getIndent() + "Not fixed diagnostics:       " + str( len( notFixed )) ) 
		print (self.getIndent() + "New diagnostics:             " + str( len( new )) 		) 

	def execute( self ):
		session = self.connect()
		newLaunch = None
		oldLaunch = None
		for launch in reversed( session.query( Tables.Launch ).all() ):
			newLaunch = oldLaunch
			oldLaunch = launch
			if newLaunch:
				self.showDifference(oldLaunch, newLaunch)
				print "\n"
			print "################################################################"
			print launch


class InitializeCommandExecutor( CommandExecutor ):
	def __init__( self, **_args ):
		super( InitializeCommandExecutor, self ).__init__( _args['dest_dir'] )
		
		self.__printSuccessMessage = True
		if 'print_success_message' in _args:
			self.__printSuccessMessage = _args['print_success_message']

	def execute( self ):
		if not os.path.exists( self.getDBContainingDir() ):
			try:
				os.makedirs( self.getDBContainingDir() )
			except os.error:
				raise DatabaseAccessProblem()

		if os.path.exists( self.getDBPath() ):
			print( "ERROR: Database is already intialized at " + self.getDBPath() )
			return

		self.connect(_canBeNonexistent = True)
		Tables.initializeTables( self.getEngine() )

		if self.__printSuccessMessage:
			print( "Database has been successfully initialized at " + self.getDBPath() )


class CleanCommandExecutor( CommandExecutor ):
	def __init__( self, **_args ):
		super( CleanCommandExecutor, self ).__init__( os.getcwd() )
		self.__dontCreate = _args['remove']
	def execute( self ):
		if not os.path.exists( self.getDBPath() ):
			return
		self.checkDatabaseAvailability()
		try:
			os.remove( self.getDBPath() )
		except os.error:
			raise DatabaseAccessProblem()

		if not self.__dontCreate:
			InitializeCommandExecutor( dest_dir=self.getDBContainingDir(), print_success_message = False ).execute()
		print( "Database has been cleaned successfully.")




class BrowseCommandExecutor( CommandExecutor ):
	def __init__( self, **_args ):
		super( BrowseCommandExecutor, self ).__init__( os.getcwd() )
		self.__n = _args[ 'n' ]
		self.__browseAll = _args['all']
	def execute( self ):
		session = self.connect()
		launch = session.query( Tables.Launch ).filter( Tables.Launch.id == self.__n ).one()
		print launch
		print "################################################################"
		for diag in (launch.diagnostics if self.__browseAll else launch.valid_diagnostics):
			print "\n",
			print diag
			print "################################################################"

class ShowCommandExecutor( CommandExecutor ):
	def __init__( self, **_args ):
		super( ShowCommandExecutor, self ).__init__( os.getcwd() )
		self.__id = _args[ 'id' ]
	def execute( self ):
		session = self.connect()
		diag = session.query( Tables.Diagnostic ).filter( Tables.Diagnostic.issue_hash == self.__id ).one()
		print diag
		print "Diagnostic was appeared in following scan-build's runs:\n"
		showSeparationLine = False
		for launch in diag.launches:
			if showSeparationLine:
				print "----------------------------------------------\n"
			print launch
			showSeparationLine = True

# Show false-positives
class SFPCommandExecutor( CommandExecutor ):
	def __init__( self, **_args ):
		super( SFPCommandExecutor, self ).__init__( os.getcwd() )
	def execute( self ):
		session = self.connect()
		diags = session.query( Tables.Diagnostic ).filter( Tables.Diagnostic.false_positive == True ).all()
		showSeparationLine = False
		for diag in diags:
			if showSeparationLine:
				print "----------------------------------------------\n"
			print diag
			showSeparationLine = True

class MarkCommandExecutor( CommandExecutor ):
	def __init__( self, **_args ):
		super( MarkCommandExecutor, self ).__init__( os.getcwd() )
		self.__id = _args[ 'id' ]
		self.__status = _args[ 'status' ]
	def execute( self ):
		session = self.connect()
		# TODO: handle incorrect diag's id
		diag = session.query( Tables.Diagnostic ).filter( Tables.Diagnostic.issue_hash == self.__id ).one()
		diag.false_positive = (self.__status == 'false-positive')
		session.commit()
		print "Diagnostic " + self.__id + "marked as " + self.__status

	
###############################################################################
# Entry point:

def main():

	import argparse
	top_parser = argparse.ArgumentParser(description="Tracking platform")
	top_parser.add_argument('--version', action='version', version='Tracking Platform 0.1')
	subparsers = top_parser.add_subparsers(help='sub-command help')
	
	# initialize command
	parser_initialize = subparsers.add_parser(
		'init', 
		description="Initializes database", 
		help='Initializes database in a current directory.')
	parser_initialize.set_defaults(executor=InitializeCommandExecutor)
	parser_initialize.add_argument('dest_dir', help="Directory where database will be placed.", nargs = '?', default = '.')


	# add command
	parser_add = subparsers.add_parser(
		'add', 
		description="Adds results to database", 
		help="Adds scan-build's results to the database.")
	parser_add.set_defaults(executor=AddCommandExecutor)
	parser_add.add_argument('--few-runs', dest = 'fewruns', action='store_true', help="Assumes directory containing a few scan-build's runs and adds all of them.")
	parser_add.add_argument('result_dir', help="Directory which was produced by one scan-build's run.")


	# clean command
	parser_clean = subparsers.add_parser(
		'clean', 
		description="Cleans the database", 
		help="Completely cleans the database")
	parser_clean.set_defaults(executor=CleanCommandExecutor)
	parser_clean.add_argument('--remove', dest = 'remove', action='store_true', help="Removes database file completely.")

	# log command
	parser_log = subparsers.add_parser(
		'log', 
		description="Shows list of scan-build's runs", 
		help="Shows list of all scan-build's runs that have been added to the database.")
	parser_log.set_defaults(executor=LogCommandExecutor)


	# browse command
	parser_browse = subparsers.add_parser(
		'browse', 
		description="Shows list of diagnostics", 
		help="Shows all diagnostics for specified number of scan-build's run.")
	parser_browse.set_defaults(executor=BrowseCommandExecutor)
	parser_browse.add_argument('-a', '--all', dest = 'all', action='store_true', help="Browses false-positive diagnostics too.")
	parser_browse.add_argument('n', type=int, help="Directory which was produced by one scan-build's run.")
	

	# show command
	parser_show = subparsers.add_parser(
		'show', 
		description="Show diagnostic by unique id", 
		help="Show diagnostic by unique id")
	parser_show.set_defaults(executor=ShowCommandExecutor)
	parser_show.add_argument('id', help="Diagnostic's unique id.")


	# show-false-positives command
	parser_sfp = subparsers.add_parser(
		'show-false-positives', 
		description="Shows all false-positive diagnostics", 
		help="Shows all false-positive diagnostics")
	parser_sfp.set_defaults(executor=SFPCommandExecutor)


	# mark command
	parser_mark = subparsers.add_parser(
		'mark', 
		description="Marks or unmarks false-positive status of diagnostic", 
		help="Marks or unmarks false-positive status of diagnostic")
	parser_mark.set_defaults(executor=MarkCommandExecutor)
	parser_mark.add_argument('status', choices=['false-positive','valid'], help="marking status")
	parser_mark.add_argument('id', help="Diagnostic's unique id.")


	# parse command line arguments
	given_args = top_parser.parse_args()
	commandExecutor = given_args.executor(**vars( given_args ) )
	try:
		commandExecutor.execute()
	except sqlalchemy.orm.exc.NoResultFound:
		print ( "ERROR: No objects were found." )
	except NoInitializedDatabase:
		print( "ERROR: No initialized database in the current directory. Do 'tracking-platform init' before.")
	except DatabaseAccessProblem:
		print( "ERROR: Problem with accessing database." ) 

if __name__ == '__main__':
	main()